[tox]
requires =
    tox-uv

[testenv:check-docs-links]
description = validate links in HTML docs
changedir = docs
extras =
    docs
commands =
    sphinx-build -W -b linkcheck . _build/html

[testenv:build-docs]
description = build the HTML docs
set_env =
    # Suppress display of matplotlib plots generated during docs build, if any
    MPLBACKEND=agg
extras = 
    docs
commands =
    sphinx-build -W docs docs/_build

[testenv]
description =
    run tests
    devdeps: with the latest developer version of third-party dependencies
    oldestdeps: with the oldest supported versions of required dependencies
    warnings: treating warnings as errors
    cov: with coverage
    xdist: in parallel
pass_env =
    HOME
    CI
    TOXENV
    CRDS_*
    TEST_BIGDATA
    CODECOV_*
set_env =
    devdeps: UV_INDEX = https://pypi.anaconda.org/liberfa/simple https://pypi.anaconda.org/astropy/simple https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
    devdeps: UV_INDEX_STRATEGY = unsafe-any-match
extras =
    test
uv_resolution =
    oldestdeps: lowest-direct
deps =
    xdist: pytest-xdist
    cov: pytest-cov >= 4.1.0
    devdeps: -r requirements-dev.txt
package =
    # necessary so that C extensions are available for import; see https://github.com/spacetelescope/jwst/issues/7386#issuecomment-1344371482
    !pyargs: editable
    pyargs: wheel
commands_pre =
    {list_dependencies_command}
commands =
    pytest \
    cov: --cov . --cov-report xml --cov-report term-missing \
    warnings: -W error \
    xdist: -n auto \
    {posargs}
