requires = ["tox>=4.50"]
env_list = [{ product = [
  { prefix = "py3", start = 11, stop = 14 },
  ["cov"],
  ["xdist"],
] }]

[env_run_base]
factors = [["cov"], ["xdist"]]
pass_env = [
  "TOXENV",
  "CI",
  "CODECOV_*",
  "HOME",
  "STRICT_VALIDATION",
  "PASS_INVALID_VALUES",
  "VALIDATE_ON_ASSIGNMENT",
  "CRDS_*",
  "TEST_BIGDATA",
]
deps = [
  "pytest>=9",
  { replace = "if", condition = "factor.cov", then = "pytest-cov" },
  { replace = "if", condition = "factor.xdist", then = "pytest-xdist" },
]
extras = ["test"]
commands = [
  ["pytest", { replace = "if", condition = "factor.cov", then = [
    "--cov",
    "--cov-report",
    "xml:{toxinidir}/coverage.xml",
    "--cov-report",
    "term-missing",
  ], extend = true }, { replace = "if", condition = "factor.xdist", then = [
    "--num-processes",
    "auto",
  ], extend = true }, { replace = "posargs", extend = true }],
]
