name: changelog

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ "{{" }} github.workflow {{ "}}" }}-${{ "{{" }} github.event.pull_request.number || github.ref {{ "}}" }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    # TODO: Pin to a release tag after the reusable workflow is merged into main.
    uses: spacetelescope/stsci-package-template/.github/workflows/reusable-changelog.yml@main
