{%- raw %}
name: upstream template conflicts

on:
  pull_request:
    paths:
      - '**.rej'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  conflicts:
    # TODO: Pin to a release tag after the reusable workflow is merged into main.
    uses: spacetelescope/stsci-package-template/.github/workflows/reusable-conflicts.yml@main
{%- endraw %}
