name: label

on:
  pull_request:

concurrency:
  group: ${{ "{{" }} github.workflow {{ "}}" }}-${{ "{{" }} github.event.pull_request.number || github.ref {{ "}}" }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  label:
    # TODO: Pin to a release tag after the reusable workflow is merged into main.
    uses: spacetelescope/stsci-package-template/.github/workflows/reusable-label.yml@main
