name: build

on:
  pull_request:
  release:
    types: [released]
  workflow_dispatch:

concurrency:
  group: ${{ "{{" }} github.workflow {{ "}}" }}-${{ "{{" }} github.event.pull_request.number || github.ref {{ "}}" }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    # TODO: Pin to a release tag after the reusable workflow is merged into main.
    uses: spacetelescope/stsci-package-template/.github/workflows/reusable-build.yml@main
    permissions:
      contents: read
      id-token: write
      attestations: write
    with:
      package_name: {{ cookiecutter.package_name }}
      python_c_extensions: {% if cookiecutter.python_c_extensions %}true{% else %}false{% endif %}
