name: tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ "{{" }} github.workflow {{ "}}" }}-${{ "{{" }} github.event.pull_request.number || github.ref {{ "}}" }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    # TODO: Pin to a release tag after the reusable workflow is merged into main.
    uses: spacetelescope/stsci-package-template/.github/workflows/reusable-tests.yml@main
    permissions:
      contents: read
    with:
      task_runner: {{ cookiecutter.task_runner }}
      crds_observatory: {{ cookiecutter.crds_observatory }}
