name: tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
    tags:  
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ "{{" }} github.workflow {{ "}}" }}-${{ "{{" }} github.event.pull_request.number || github.ref {{ "}}" }}
  cancel-in-progress: true

permissions: {}

env:
  PYTHON_VERSIONS: 3.9 3.10 3.11 3.12 3.13 3.14
{%- if cookiecutter.crds_observatory != 'none' %}
  CRDS_PATH: /tmp/data/crds_cache
  CRDS_OBSERVATORY: {{ cookiecutter.crds_observatory }}
  CRDS_SERVER_URL: https://{{ cookiecutter.crds_observatory }}-crds.stsci.edu
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
{%- endif %}

jobs:
  supported-pythons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3"
      - run: pip install packaging tomli
      - name: convert Python version(s) into JSON list
        id: versions
        shell: python
        run: |
          import os
          import json

          import tomli
          from packaging.specifiers import SpecifierSet
          from packaging.version import Version

          with open("pyproject.toml", "rb") as pyproject_toml_file:
            version_requirements = SpecifierSet(tomli.load(pyproject_toml_file)["project"]["requires-python"])

          versions = [str(version) for version in sorted([Version(version) for version in os.environ["PYTHON_VERSIONS"].split() if version in version_requirements])]

          with open(os.environ["GITHUB_OUTPUT"], "a") as github_output:
              print(f"json={json.dumps(versions)}", file=github_output)
              print(f"oldest={versions[0]}", file=github_output)
              print(f"latest={versions[-1]}", file=github_output)
    outputs:
      python-version-json: ${{ "{{" }} steps.versions.outputs.json {{ "}}" }}
      oldest: ${{ "{{" }} steps.versions.outputs.oldest {{ "}}" }}
      latest: ${{ "{{" }} steps.versions.outputs.latest {{ "}}" }}
{%- if cookiecutter.crds_observatory != 'none' %}
  crds:
    runs-on: ubuntu-latest
    steps:
      - id: latest-context
        run: >
          echo latest-context=$(
            curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ "{{" }} env.CRDS_OBSERVATORY {{ "}}" }}", "latest"], "id": 1}' ${{ "{{" }} env.CRDS_SERVER_URL {{ "}}" }}/json/ --retry 8 --connect-timeout 10 |
            python -c "import sys, json; print(json.load(sys.stdin)['result'])"
          ) >> $GITHUB_OUTPUT
    outputs:
      path: ${{ "{{" }} env.CRDS_PATH {{ "}}" }}
      server-url: ${{ "{{" }} env.CRDS_SERVER_URL {{ "}}" }}
      context: ${{ "{{" }} steps.latest-context.outputs.latest-context {{ "}}" }}
      client-retry-count: ${{ "{{" }} env.CRDS_CLIENT_RETRY_COUNT {{ "}}" }}
      client-retry-delay-seconds: ${{ "{{" }} env.CRDS_CLIENT_RETRY_DELAY_SECONDS {{ "}}" }}
{%- endif %}
  test:
    needs:
      - supported-pythons
{%- if cookiecutter.crds_observatory != 'none' %}
      - crds
{%- endif %}
{%- if cookiecutter.task_runner != 'tox' %}
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-latest"]
        python-version: ${{ "{{" }} fromJSON(needs.supported-pythons.outputs.python-version-json) {{ "}}" }}
        coverage: [false]
        include:
          - name: run tests (oldest supported Python, ubuntu-latest)
            runs-on: "ubuntu-latest"
            python-version: "${{ "{{" }} needs.supported-pythons.outputs.oldest {{ "}}" }}"
          - name: run tests with coverage (latest supported Python, ubuntu-latest)
            runs-on: "ubuntu-latest"
            python-version: "${{ "{{" }} needs.supported-pythons.outputs.latest {{ "}}" }}"
            coverage: true
          - name: run tests (latest supported Python, macos-latest)
            runs-on: "macos-latest"
            python-version: "${{ "{{" }} needs.supported-pythons.outputs.latest {{ "}}" }}"
    name: ${{ "{{" }} matrix.name || format('run tests (Python {0}, {1})', matrix.python-version, matrix.runs-on) {{ "}}" }}
    runs-on: ${{ "{{" }} matrix.runs-on {{ "}}" }}
{%- if cookiecutter.crds_observatory != 'none' %}
    env:
      CRDS_CONTEXT: ${{ "{{" }} needs.crds.outputs.context {{ "}}" }}
{%- endif %}
    steps:
{%- if cookiecutter.crds_observatory != 'none' %}
      - name: cache CRDS reference files retrieved during testing
        uses: actions/cache@v5
        with:
          path: ${{ "{{" }} env.CRDS_PATH {{ "}}" }}
          key: ${{ "{{" }} env.CRDS_CONTEXT {{ "}}" }}
{%- endif %}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
{%- if cookiecutter.task_runner == 'none' %}
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ "{{" }} matrix.python-version {{ "}}" }}
      - run: pip install ".[test]" ${{ "{{" }} matrix.coverage && 'coverage pytest-cov' || '' {{ "}}" }}
      - run: pytest ${{ "{{" }} matrix.coverage && '--cov' || '' {{ "}}" }}
{%- elif cookiecutter.task_runner == 'nox' %}
      - uses: wntrblm/nox@5a277b752f6094150e25237d47c34168e2b7526e # 2026.02.09
        with:
            python-versions: ${{ "{{" }} matrix.python-version {{ "}}" }}
            session: test${{ "{{" }} matrix.coverage && '_with_coverage' || '' {{ "}}" }}
{%- endif %}
      - if: matrix.coverage
        name: report coverage to summary
        run: |
          coverage combine
          echo '## Coverage Report' >> $GITHUB_STEP_SUMMARY
          coverage report -i -m --format=markdown | tee -a $GITHUB_STEP_SUMMARY
{%- elif cookiecutter.task_runner == 'tox' %}
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@e5af21e4ae37af089a73bb032e10b78b0e746174 # v3.0.1
    with:
{%- if cookiecutter.crds_observatory != 'none' %}
      setenv: |
        CRDS_PATH: ${{ "{{" }} needs.crds.outputs.path {{ "}}" }}
        CRDS_SERVER_URL: ${{ "{{" }} needs.crds.outputs.server-url {{ "}}" }}
        CRDS_CONTEXT: ${{ "{{" }} needs.crds.outputs.context {{ "}}" }}
        CRDS_CLIENT_RETRY_COUNT: ${{ "{{" }} needs.crds.outputs.client-retry-count {{ "}}" }}
        CRDS_CLIENT_RETRY_DELAY_SECONDS: ${{ "{{" }} needs.crds.outputs.client-retry-delay-seconds{{ "}}" }}
      cache-path: ${{ "{{" }} needs.crds.outputs.path {{ "}}" }}
      cache-key: crds-${{ "{{" }} needs.crds.outputs.context {{ "}}" }}
{%- endif %}
      envs: |
        - name: run tests (oldest supported Python, ubuntu-latest)
          linux: py3
          python-version: ${{ "{{" }} needs.supported-pythons.outputs.oldest {{ "}}" }}
        - linux: py*
        - name: run tests with coverage (latest supported Python, ubuntu-latest)
          linux: py3-cov
          python-version: ${{ "{{" }} needs.supported-pythons.outputs.latest {{ "}}" }}
          pytest-results-summary: true
          coverage: github
        - name: run tests (latest supported Python, macos-latest)
          macos: py3
          python-version: ${{ "{{" }} needs.supported-pythons.outputs.latest {{ "}}" }}
      artifact-path: |
        results.xml
{%- endif %}
