# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: CI

on:
  push:
    branches:
    - main  # GitHub now defaults to 'main' as the name of the primary branch. Change this as needed.
  #  tags: # run CI if specific tags are pushed
  pull_request:
  #  branches: # only build on PRs against 'main' if you need to further limit when CI is run.
  #  - main

jobs:
  # Github Actions supports ubuntu, windows, and macos virtual environments:
  # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
  ci_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure}}
    strategy:
      matrix:
        include:
          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle
            allow_failure: false

          - name: PEP 517
            os: ubuntu-latest
            python: 3.x
            toxenv: pep517
            allow_failure: false

          - name: Security audit
            os: ubuntu-latest
            python: 3.x
            toxenv: securityaudit
            allow_failure: false

          - name: Python 3.7 with oldest supported dependencies
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test-oldestdeps
            allow_failure: false

          - name: Python 3.9 with coverage checking
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test-cov
            allow_failure: false

          - name: OS X - Python 3.8
            os: macos-latest
            python: 3.8
            toxenv: py38-test
            allow_failure: false

          - name: Windows - Python 3.8
            os: windows-latest
            python: 3.8
            toxenv: py38-test
            allow_failure: false

          - name: Python 3.9 with latest dev versions of key dependencies
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test-devdeps
            allow_failure: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox codecov
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}
    # Activate your repo on codecov.io first.
    - name: Upload coverage to codecov
      if: "contains(matrix.toxenv, '-cov')"
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
